.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ROOTS" "1" "June 2013" "" ""
.
.SH "NAME"
\fBroots\fR \- a toolkit for quickly building beautiful websites
.
.SH "SYNOPSIS"
\fBroots new <name>\fR \-\-\fItemplate\fR
.
.br
\fBroots template <command>\fR
.
.br
\fBroots compile\fR \-\-no\-compress
.
.br
\fBroots watch\fR
.
.br
\fBroots deploy\fR \fIname\fR \-\-\fIservice\fR
.
.br
\fBroots version\fR
.
.br
\fBroots pkg\fR \fIcommand\fR
.
.br
\fBroots plugin\fR \fIcommand\fR
.
.SH "DESCRIPTION"
Roots exposes a variety of commands for creating, managing, compiling, and deploying websites\. Commands are listed and documented below\.
.
.P
github repo \fIhttps://github\.com/jenius/roots\fR
.
.SH "NEW"
\fBnew\fR, \fB<name>\fR, \-\-\fItemplate\fR
.
.br
create a new roots project called \fIname\fR\.
.
.P
templates:
.
.IP "" 4
.
.nf

\- default (jade, stylus, coffeescript) \- default
\- ejs (ejs, stylus, coffeescript)
\- min (default stack, no comments and uses jade layouts)
\- basic (html, css, javascript, no layouts)
\- blog (blog example optimized for dynamic content)
.
.fi
.
.IP "" 0
.
.SH "TEMPLATE"
\fBtemplate\fR, \fB<command>\fR
.
.br
manage roots project templates\.
.
.P
commands:
.
.IP "" 4
.
.nf

\- add, <name> <git\-url> (git clone will download the template)
\- remove, <name> (be careful with this)
\- default, <name> (sets a template to be the default for roots new)
.
.fi
.
.IP "" 0
.
.SH "COMPILE"
\fBcompile\fR, \-\-\fIno\-compress\fR
.
.br
compile, compress, and minify the project to \fBpublic\fR, adding the option \fIno\-compress\fR will bypass the compression\.
.
.SH "WATCH"
\fBwatch\fR
.
.br
watch your project and compile/reload whenever a file is saved\. does not work for roots\-express or roots\-rails\.
.
.SH "DEPLOY"
\fBdeploy\fR, \fIname\fR, \-\-\fIservice\fR
.
.br
configure, compile, commit, and deploy your project\. \fIname\fR optional for heroku\.
.
.IP "" 4
.
.nf

services:
  \- heroku \- default
  \- nodejitsu
  \- gh\-pages
.
.fi
.
.IP "" 0
.
.SH "VERSION"
\fBversion\fR
.
.br
print the version of the current roots install\.
.
.SH "PKG"
\fBpkg\fR, \fB<command>\fR
.
.br
exposes a package manager\'s interface\. type \fBroots pkg\fR to display the package manager\'s options\. any command given after \fBpkg\fR is delegated to the package manager\.
.
.P
package managers:
.
.IP "" 4
.
.nf

\- bower (http://bower\.io) \- default
\- cdnjs (https://github\.com/jenius/cli\-js)
.
.fi
.
.IP "" 0
.
.P
you can change your package manager via the \fB~/\.rootsrc\fR file\.
.
.SH "PLUGIN"
\fBplugin\fR, \fB<command>\fR
.
.br
manages plugins (user\-generated roots compilers)\.
.
.P
commands:
.
.IP "" 4
.
.nf

\- generate \-\-js (optional, generates a javascript template rather than coffeescript)
\- install <username>/<repo> (must provide a username/repo on github)
.
.fi
.
.IP "" 0
.
.SH "DOCUMENTATION"
Full docs can be found at http://roots\.cx
