.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "ROOTS" "1" "January 2013" "" ""
.
.SH "NAME"
\fBroots\fR \-\- a toolkit for quickly building beautiful websites
.
.SH "NAME"
roots \-\- refer to http://roots\.cx for details
.
.SH "SYNOPSIS"
\fBroots\fR <option>
.
.SH "DESCRIPTION"
Roots exposes a variety of commands for creating, managing, compiling, and deploying websites\.
.
.P
The following commands are available:
.
.IP "\(bu" 4
\fBnew\fR, \fB<name>\fR, \-\-<type>
create a new roots project called <name>\. <type> can be <express> or <basic>\.
.
.IP "\(bu" 4
\fBcompile\fR, \-\-<no\-compress>
compile, compress, and minify the project to \fBpublic\fR, adding the option <no\-compress> will bypass the compression
.
.IP "\(bu" 4
\fBwatch\fR
watch your project and compile/reload whenever a file is saved\. does not work for roots\-express or roots\-rails
.
.IP "\(bu" 4
\fBdeploy\fR, \fB<name>\fR
configure, compile, commit, and deploy your project to heroku
.
.IP "\(bu" 4
\fBupdate\fR
upgrade to the latest version of roots
.
.IP "\(bu" 4
\fBversion\fR
print the version of the current roots install
.
.IP "\(bu" 4
\fBjs\fR, \fB<command>\fR, \fB<option>\fR
exposes bower\'s interface\. type \fBroots js\fR for help with bower
.
.IP "\(bu" 4
\fBplugin\fR, \fB<command>\fR, \fB<option>\fR
manages plugins\. command can be \fBgenerate\fR with an optional flag of \fB\-\-js\fR for generate a coffeescript or javascript plugin template\. command can be \fBinstall\fR with the option being \fBusername/repo\fR on github to install a plugin into the /plugins folder
.
.IP "" 0
.
.SH "DOCUMENTATION"
Full docs can be found at http://roots\.cx
.
.SH "AUTHOR"
Jeff Escalante (http://jenius\.me) and contributors
